name: Hello world!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
        - name: Greet hello
          run: |
            echo "Hello World!"



